vit:
  patch_dim: 16
  input_channels: 3
  num_classes: 5
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  dropout: 0.1
  attention_dropout: 0.0
  eps: 1e-05
  ff_dim: 3072
  dim: 224

train:
  data: 'data'
  batch_size: 192
  eval_batch_size: 16
  scheduler_type: 'warmup-cosine'
  max_epochs: 75
  warmup_epochs: 10
  use_bitsandbytes: True
  optim: 'adamw'
  lr: 7e-4
  device: 'cuda'
  save_path: 'weights'
  eval_epoch: 1
  log_epoch: 1
  save_epoch: 5
  log_path: 'logs'
  early_stopping: 75
  base_dir: 'DATASET-DIR'
  finetuning: True
  checkpoint: 'PRETRAINED-WEIGHTS'
  freeze_model: True
  from_checkpoint: False

inference:
  checkpoint: 'TRAINED-WEIGHTS'

overfit_one_batch:
  tolerance: 1e-6
  max_steps: 150
  overfit: False
  logging_steps: 10
